apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - monitoringstack.yaml
  - podmonitor-istio-proxies.yaml
  - servicemonitor-istiod.yaml
  - uiplugin-tracing.yaml
  - uiplugin-logging.yaml
  - uiplugin-dashboards.yaml
  - uiplugin-monitoring.yaml
  - uiplugin-troubleshooting-panel.yaml

