apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cluster Observability Operator
# Provides: MonitoringStack, UIPlugins (tracing, logging, dashboards, etc.)

resources:
  - namespace.yaml
  - subscription.yaml
