apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - opa-istio-config.yaml
  - opa-policy.yaml
  - service-entry.yaml
  - authorization-policy.yaml
  - httproute.yaml

