apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./bookinfo-http-route.yaml
- ./bookinfo-gateway.yaml

patchesStrategicMerge:
- namespace-patch.yaml

# Note: Using 'labels' instead of 'commonLabels' to avoid adding labels to Service selectors
# which would break pod matching (pods don't get these labels from Kustomize automatically)
labels:
- pairs:
    app.kubernetes.io/part-of: bookinfo
  includeSelectors: false