apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- frontend.yaml
- backend.yaml
- database.yaml
- network-policies.yaml
- traffic-generator.yaml
- attacker.yaml

commonLabels:
  demo: network-policy

